#!/usr/bin/env python3
"""
Fix "SNIPPETS_MANAGEMENT_FOLDER env var is not set" in self-hosted Supabase Studio.

Supabase Studio refuses to load the SQL snippet library when the `studio` service
starts without `SNIPPETS_MANAGEMENT_FOLDER`:

    SNIPPETS_MANAGEMENT_FOLDER env var is not set. Please set it to use snippets properly.

Projects generated by older versions of `supabase_setup.py` (and any hand-written
compose file) are missing that variable *and* the bind mount that persists
`volumes/snippets/snippets.json`, so snippets either error out or vanish on the next
`docker compose up`.

This tool patches a compose file in place (idempotently, with a timestamped backup):

  - adds SNIPPETS_MANAGEMENT_FOLDER and EDGE_FUNCTIONS_MANAGEMENT_FOLDER to `studio.environment`
  - adds the `./volumes/snippets` (rw) and `./volumes/functions` (ro) mounts to `studio.volumes`
  - creates the host directories so Docker/Podman does not create them root-owned

Usage:
  python3 update_studio_snippets.py                        # fix ./docker-compose.yml
  python3 update_studio_snippets.py --project-name myapp   # fix projects/myapp
  python3 update_studio_snippets.py --project-path /srv/app  # fix an arbitrary project dir
  python3 update_studio_snippets.py --all-projects --check   # audit repo root + projects/*
  python3 update_studio_snippets.py --project-name myapp --dry-run

Exit codes: 0 = nothing to fix or fixed, 1 = findings in --check mode, 2 = usage/IO error.
"""
from __future__ import annotations

import argparse
import datetime
import os
import re
import sys
from pathlib import Path

SNIPPETS_ENV = "SNIPPETS_MANAGEMENT_FOLDER"
SNIPPETS_CONTAINER_DIR = "/app/snippets"
SNIPPETS_HOST_DIR = "volumes/snippets"

EDGE_ENV = "EDGE_FUNCTIONS_MANAGEMENT_FOLDER"
EDGE_CONTAINER_DIR = "/app/edge-functions"
EDGE_HOST_DIR = "volumes/functions"

# (env var, container path, host dir, mount mode)
WANTED = [
    (SNIPPETS_ENV, SNIPPETS_CONTAINER_DIR, SNIPPETS_HOST_DIR, "z"),
    (EDGE_ENV, EDGE_CONTAINER_DIR, EDGE_HOST_DIR, "ro,z"),
]

NOTE_TEXT = "added by update_studio_snippets.py (Studio snippets / Edge Functions editor folders)"


def _note(indent: int) -> str:
    return " " * indent + "# " + NOTE_TEXT


# --------------------------------------------------------------------------------------
# Minimal indentation-aware YAML editing, so comments and formatting survive the patch
# --------------------------------------------------------------------------------------
def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" \t"))


def is_blank_or_comment(line: str) -> bool:
    stripped = line.strip()
    return not stripped or stripped.startswith("#")


def block_end(lines: list[str], start: int, indent: int) -> int:
    """Index (exclusive) just past the last line belonging to the mapping/list at `start`."""
    end = start + 1
    for i in range(start + 1, len(lines)):
        if is_blank_or_comment(lines[i]):
            continue
        if indent_of(lines[i]) <= indent:
            break
        end = i + 1
    return end


def child_indent(lines: list[str], start: int, end: int) -> int | None:
    """Indentation used by the children of a block (None when the block is empty)."""
    indents = [indent_of(lines[i]) for i in range(start, end) if not is_blank_or_comment(lines[i])]
    return min(indents) if indents else None


def find_key(lines: list[str], start: int, end: int, indent: int, key: str) -> int | None:
    """Index of `key:` at exactly `indent` within [start, end)."""
    pattern = re.compile(rf"^{re.escape(key)}\s*:(?:\s|$)")
    for i in range(start, end):
        if is_blank_or_comment(lines[i]):
            continue
        if indent_of(lines[i]) == indent and pattern.match(lines[i].strip()):
            return i
    return None


def studio_block(lines: list[str]) -> tuple[int, int, int] | None:
    """(start, end, indent) of the `studio:` service mapping, or None."""
    top = find_key(lines, 0, len(lines), 0, "services")
    if top is None:
        return None
    svc_start, svc_end = top + 1, block_end(lines, top, 0)
    indent = child_indent(lines, svc_start, svc_end)
    if indent is None:
        return None
    studio = find_key(lines, svc_start, svc_end, indent, "studio")
    if studio is None:
        return None
    return studio, block_end(lines, studio, indent), indent


def mount_for(container_dir: str, host_dir: str, mode: str) -> str:
    return f"./{host_dir}:{container_dir}:{mode}"


# --------------------------------------------------------------------------------------
# Analysis / patching
# --------------------------------------------------------------------------------------
def analyze_compose(path: Path) -> dict:
    """Report what the studio service of a compose file is missing."""
    info = {
        "file": path,
        "exists": path.is_file(),
        "error": None,
        "missing_env": [],
        "missing_mounts": [],
    }
    if not info["exists"]:
        info["error"] = "file not found"
        return info

    lines = path.read_text(encoding="utf-8").splitlines()
    studio = studio_block(lines)
    if studio is None:
        info["error"] = "no 'studio' service found"
        return info

    start, end, _ = studio
    text = "\n".join(lines[start:end])
    info["missing_env"] = [env for env, _c, _h, _m in WANTED if env not in text]
    info["missing_mounts"] = [
        mount_for(container, host, mode)
        for _env, container, host, mode in WANTED
        if f":{container}" not in text
    ]
    return info


def patch_compose(path: Path, dry_run: bool = False) -> list[str]:
    """Insert missing env vars / bind mounts into the studio service. Returns change notes."""
    info = analyze_compose(path)
    if info["error"]:
        raise RuntimeError(info["error"])
    if not info["missing_env"] and not info["missing_mounts"]:
        return []

    original = path.read_text(encoding="utf-8")
    lines = original.splitlines()
    changes: list[str] = []

    # 1. environment: prefer mapping style (`KEY: value`), honour list style if that is used
    start, end, indent = studio_block(lines)
    child = child_indent(lines, start + 1, end) or indent + 2
    env_at = find_key(lines, start, end, child, "environment")
    wanted_env = [(env, container) for env, container, _host, _mode in WANTED if env in info["missing_env"]]
    if wanted_env:
        entry_indent = child + 2
        added_env: list[str] = []
        if env_at is None:
            block = [f"{' ' * child}environment:", _note(entry_indent)]
            block += [f"{' ' * entry_indent}{env}: {value}" for env, value in wanted_env]
            lines[start + 1:start + 1] = block
            added_env = [env for env, _ in wanted_env]
        else:
            env_end = block_end(lines, env_at, child)
            env_child = child_indent(lines, env_at + 1, env_end) or entry_indent
            env_text = "\n".join(lines[env_at:env_end])
            list_style = any(
                lines[i].strip().startswith("- ")
                for i in range(env_at + 1, env_end)
                if not is_blank_or_comment(lines[i])
            )
            missing_here = [(env, value) for env, value in wanted_env if env not in env_text]
            additions = [
                f"{' ' * env_child}- {env}={value}" if list_style else f"{' ' * env_child}{env}: {value}"
                for env, value in missing_here
            ]
            if additions:
                lines[env_end:env_end] = [_note(env_child)] + additions
                added_env = [env for env, _ in missing_here]
        if added_env:
            changes.append("added " + ", ".join(added_env) + " to studio environment")

    # 2. volumes: bind mounts (recomputed - step 1 may have shifted line numbers)
    start, end, indent = studio_block(lines)
    child = child_indent(lines, start + 1, end) or indent + 2
    text = "\n".join(lines[start:end])
    pending = [
        mount_for(container, host, mode)
        for _env, container, host, mode in WANTED
        if f":{container}" not in text
    ]
    if pending:
        vol_at = find_key(lines, start, end, child, "volumes")
        if vol_at is None:
            entry_indent = child + 2
            block = [f"{' ' * child}volumes:", _note(entry_indent)] + [f"{' ' * entry_indent}- {m}" for m in pending]
            lines[end:end] = block
        else:
            vol_end = block_end(lines, vol_at, child)
            vol_child = child_indent(lines, vol_at + 1, vol_end) or child + 2
            lines[vol_end:vol_end] = [_note(vol_child)] + [f"{' ' * vol_child}- {m}" for m in pending]
        changes.append("added bind mounts " + ", ".join(pending))

    updated = "\n".join(lines) + ("\n" if original.endswith("\n") else "")
    if updated == original:
        return changes

    if dry_run:
        changes.append("dry run - nothing written")
    else:
        backup = path.with_suffix(path.suffix + ".bak." + datetime.datetime.now().strftime("%Y%m%d%H%M%S"))
        backup.write_text(original, encoding="utf-8")
        path.write_text(updated, encoding="utf-8")
        changes.append(f"backup written to {backup.name}")
    return changes


def ensure_host_dirs(compose_path: Path, dry_run: bool = False, fix_permissions: bool = False) -> list[str]:
    """Create the bind-mount sources, so Docker does not create them root-owned."""
    notes: list[str] = []
    base = compose_path.parent
    for _env, _container, host_dir, _mode in WANTED:
        target = base / host_dir
        if not target.is_dir():
            if dry_run:
                notes.append(f"would create {host_dir}/")
                continue
            target.mkdir(parents=True, exist_ok=True)
            notes.append(f"created {host_dir}/")
        # A host dir Docker auto-created for a missing bind mount is root-owned, which is
        # why Studio can then read SNIPPETS_MANAGEMENT_FOLDER but fail to write snippets.json.
        if host_dir != SNIPPETS_HOST_DIR:
            continue
        mode = target.stat().st_mode & 0o777
        world_writable = bool(mode & 0o002)
        if fix_permissions:
            if world_writable or dry_run:
                if dry_run and not world_writable:
                    notes.append(f"would open permissions on {host_dir}/")
            else:
                try:
                    os.chmod(target, 0o777)
                    notes.append(f"chmod 0777 {host_dir}/ (Studio needs to write snippets.json)")
                except PermissionError:
                    notes.append(f"cannot chmod {host_dir}/ - it is owned by another user, use sudo")
        elif not os.access(target, os.W_OK):
            notes.append(
                f"{host_dir}/ is not writable by uid {os.getuid()}; rerun with --fix-permissions "
                f"or chown it, otherwise Studio cannot save snippets"
            )
    return notes


# --------------------------------------------------------------------------------------
# Self-test (no third-party deps): python3 update_studio_snippets.py --self-test
# --------------------------------------------------------------------------------------
_FIXTURES = {
    "legacy_project": """name: legacyapp

services:
  studio:
    container_name: legacyapp-studio
    image: supabase/studio:2026.08.24-sha-8ec45b2
    environment:
      STUDIO_PG_META_URL: http://legacyapp-meta:8080
    depends_on:
      analytics:
        condition: service_healthy

  db:
    image: supabase/postgres:17.4.1.00
""",
    "no_environment": """services:
  studio:
    image: supabase/studio
    restart: unless-stopped
""",
    "list_style": """services:
  studio:
    image: supabase/studio
    environment:
      - NODE_ENV=production
    volumes:
      - ./extra:/extra:ro
""",
    "complete": f"""services:
  studio:
    image: supabase/studio
    environment:
      {SNIPPETS_ENV}: {SNIPPETS_CONTAINER_DIR}
      {EDGE_ENV}: {EDGE_CONTAINER_DIR}
    volumes:
      - ./{SNIPPETS_HOST_DIR}:{SNIPPETS_CONTAINER_DIR}:z
      - ./{EDGE_HOST_DIR}:{EDGE_CONTAINER_DIR}:ro,z
""",
    "no_studio": """services:
  db:
    image: supabase/postgres
""",
}


def self_test() -> int:
    import tempfile

    failures = 0

    # Repo invariants: the shipped compose files/templates must already be correct.
    root = Path(__file__).resolve().parent
    repo_checks: list[tuple[str, bool]] = []
    if (root / "docker-compose.yml").is_file():
        repo_info = analyze_compose(root / "docker-compose.yml")
        repo_checks.append(
            ("root docker-compose.yml studio service", not repo_info["error"] and not repo_info["missing_env"])
        )
        repo_checks.append(("root volumes/snippets host dir", (root / SNIPPETS_HOST_DIR).is_dir()))
    generator = root / "supabase_setup.py"
    if generator.is_file():
        template = generator.read_text(encoding="utf-8")
        repo_checks.append(
            (
                "supabase_setup.py studio template",
                SNIPPETS_ENV in template
                and f"./{SNIPPETS_HOST_DIR}:{SNIPPETS_CONTAINER_DIR}" in template
                and f'"{SNIPPETS_HOST_DIR}"' in template,  # dir is created per project
            )
        )
    for label, ok in repo_checks:
        print(f"{'PASS' if ok else 'FAIL'} repo: {label}")
        if not ok:
            failures += 1

    with tempfile.TemporaryDirectory() as tmp:
        for name, compose in _FIXTURES.items():
            project = Path(tmp) / name
            (project / "volumes" / "functions").mkdir(parents=True)
            compose_file = project / "docker-compose.yml"
            compose_file.write_text(compose, encoding="utf-8")

            info = analyze_compose(compose_file)
            try:
                if name == "no_studio":
                    assert info["error"] == "no 'studio' service found"
                elif name == "complete":
                    assert not info["missing_env"] and not info["missing_mounts"], info
                    assert not patch_compose(compose_file)
                    assert compose_file.read_text(encoding="utf-8") == compose
                    assert not list(project.glob("*.bak.*")), "backup written for a clean file"
                else:
                    assert info["missing_env"] == [SNIPPETS_ENV, EDGE_ENV], info["missing_env"]
                    changes = patch_compose(compose_file)
                    assert changes, "expected change notes"
                    patched = compose_file.read_text(encoding="utf-8")
                    for env, container, _host, _mode in WANTED:
                        assert env in patched and container in patched, (name, env)
                    assert not analyze_compose(compose_file)["missing_env"]
                    assert not patch_compose(compose_file), "patch is not idempotent"
                    ensure_host_dirs(compose_file)
                    assert (project / SNIPPETS_HOST_DIR).is_dir(), "snippet dir not created"
            except AssertionError as exc:
                failures += 1
                print(f"FAIL {name}: {exc}")
                print(compose_file.read_text(encoding="utf-8"))
            else:
                print(f"PASS {name}")

    print("self-test failed" if failures else "all self-tests passed")
    return 1 if failures else 0


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------
def collect_targets(args: argparse.Namespace) -> list[tuple[Path, bool]]:
    """Targets to inspect, as (compose file, required). Missing optional targets are skipped."""
    root = Path(args.root).resolve()
    if args.compose_file:
        return [(Path(args.compose_file), True)]
    if args.project_name:
        return [(root / "projects" / args.project_name / "docker-compose.yml", True)]
    if args.project_path:
        return [(Path(args.project_path) / "docker-compose.yml", True)]
    targets: list[tuple[Path, bool]] = [(root / "docker-compose.yml", not args.all_projects)]
    if args.all_projects:
        targets.extend(
            (path, True) for path in sorted((root / "projects").glob("*/docker-compose.yml"))
        )
    return targets


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Add the SNIPPETS_MANAGEMENT_FOLDER config self-hosted Studio snippets need."
    )
    scope = parser.add_mutually_exclusive_group()
    scope.add_argument("--project-name", help="Project under <root>/projects/<name>")
    scope.add_argument("--project-path", help="Path to a generated project directory")
    scope.add_argument("--compose-file", help="Path to a specific docker-compose file")
    scope.add_argument("--all-projects", action="store_true", help="Repo root compose plus projects/*")
    parser.add_argument("--root", default=".", help="Repository root (default: cwd)")
    parser.add_argument("--check", action="store_true", help="Report only, never write (exit 1 on findings)")
    parser.add_argument("--dry-run", action="store_true", help="Print intended changes without writing")
    parser.add_argument(
        "--fix-permissions",
        action="store_true",
        help="chmod 0777 the snippet dirs so a non-root Studio process can write snippets.json",
    )
    parser.add_argument("--self-test", action="store_true", help="Run the built-in patcher fixtures and exit")
    args = parser.parse_args(argv)

    if args.self_test:
        return self_test()

    read_only = args.check or args.dry_run
    exit_code = 0
    for target, required in collect_targets(args):
        try:
            info = analyze_compose(target)
        except Exception as exc:  # pragma: no cover - defensive
            print(f"[FAIL]  {target}: {exc}")
            return 2

        if info["error"]:
            if not required and not target.exists():
                print(f"[SKIP]  {target}: no root compose file (nothing to check)")
                continue
            print(f"[SKIP]  {target}: {info['error']}")
            exit_code = 1 if args.check else 2
            continue

        needs_patch = bool(info["missing_env"] or info["missing_mounts"])

        if args.check:
            problems = [f"missing {', '.join(info['missing_env'] + info['missing_mounts'])}"] if needs_patch else []
            problems += ensure_host_dirs(target, dry_run=True, fix_permissions=args.fix_permissions)
            if problems:
                print(f"[NEEDS FIX] {target}: " + "; ".join(problems))
                exit_code = 1
            else:
                print(f"[OK]      {target}: studio snippets config present")
            continue

        try:
            changes = patch_compose(target, dry_run=args.dry_run) if needs_patch else []
            changes += ensure_host_dirs(target, dry_run=args.dry_run, fix_permissions=args.fix_permissions)
        except Exception as exc:
            print(f"[FAIL]  {target}: {exc}")
            exit_code = 2
            continue

        if not changes:
            print(f"[OK]    {target}: studio snippets config present, nothing to do")
            continue
        label = "[DRY ] " if args.dry_run else "[FIXED]"
        print(f"{label} {target}: " + "; ".join(changes))
        if not read_only and needs_patch:
            print("        next: docker compose up -d studio  (restart picks up the new env var)")

    if exit_code == 0:
        print("Studio snippets configuration is complete.")
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
